const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const TODAY=new Date().toISOString().slice(0,10);
const STATUS=['REQUESTED','CONFIRMED','CHECKED IN','IN SERVICE','READY FOR PICKUP','COMPLETED','CANCELLED','NO SHOW'];
const seed={
 customers:[
  {id:1,name:'Maria Santos',mobile:'0917 123 4567',email:'maria@example.com',address:'Imus, Cavite',visits:8,spend:12850,points:128,notes:'Prefers SMS updates.'},
  {id:2,name:'James Cruz',mobile:'0918 654 3321',email:'james@example.com',address:'Bacoor, Cavite',visits:5,spend:7460,points:74,notes:''},
  {id:3,name:'Angela Reyes',mobile:'0920 223 1190',email:'angela@example.com',address:'Las Piñas',visits:11,spend:21420,points:214,notes:'Weekend appointments preferred.'}
 ],
 pets:[
  {id:1,name:'Milo',type:'Dog',breed:'Shih Tzu',sex:'Male',ownerId:1,birthday:'2022-02-14',weight:'6.1 kg',color:'White/Brown',microchip:'',allergies:'Chicken',medical:'Sensitive skin',medications:'None',vaccination:'Updated',temperament:'Friendly',grooming:'Use hypoallergenic shampoo',preferred:'Carlo Mendoza',emergency:'Avoid chicken-based treats'},
  {id:2,name:'Luna',type:'Cat',breed:'Persian',sex:'Female',ownerId:2,birthday:'2021-10-08',weight:'4.3 kg',color:'White',microchip:'',allergies:'None known',medical:'None',medications:'None',vaccination:'Updated',temperament:'Calm',grooming:'Low-noise dryer',preferred:'Carlo Mendoza',emergency:'Keep away from loud dryers'},
  {id:3,name:'Bruno',type:'Dog',breed:'Golden Retriever',sex:'Male',ownerId:3,birthday:'2020-06-19',weight:'29 kg',color:'Golden',microchip:'985141000123456',allergies:'None known',medical:'None',medications:'None',vaccination:'Updated',temperament:'Energetic',grooming:'Deshedding shampoo',preferred:'Carlo Mendoza',emergency:''}
 ],
 staff:[
  {id:1,name:'Anna Dela Cruz',role:'MANAGER',on:true},{id:2,name:'Carlo Mendoza',role:'GROOMER',on:true},{id:3,name:'Bea Lim',role:'CASHIER',on:true},{id:4,name:'Noel Garcia',role:'PET CARE STAFF',on:false},{id:5,name:'Rica Flores',role:'INVENTORY STAFF',on:true}
 ],
 products:[
  {id:1,name:'Premium Dog Food 2kg',sku:'PE-DF-200',barcode:'480000001001',category:'Pet Food',brand:'Pet Express',supplier:'Paws Supply Co.',cost:510,price:780,stock:24,reorder:8,expiry:'2027-06-30',batch:'DF2401',location:'A1'},
  {id:2,name:'Salmon Cat Treats',sku:'PE-CT-018',barcode:'480000001002',category:'Treats',brand:'Meow Bites',supplier:'Paws Supply Co.',cost:95,price:165,stock:6,reorder:8,expiry:'2027-03-18',batch:'CT112',location:'B2'},
  {id:3,name:'Rope Tug Toy',sku:'PE-TY-044',barcode:'480000001003',category:'Toys',brand:'PlayPaw',supplier:'Happy Tails Trading',cost:120,price:245,stock:17,reorder:6,expiry:'',batch:'',location:'C1'},
  {id:4,name:'Pet Shampoo 500ml',sku:'PE-GR-051',barcode:'480000001004',category:'Grooming',brand:'CleanPaws',supplier:'Happy Tails Trading',cost:175,price:310,stock:4,reorder:5,expiry:'2027-01-15',batch:'GR55',location:'D2'},
  {id:5,name:'Blue Harness M',sku:'PE-AC-032',barcode:'480000001005',category:'Accessories',brand:'WalkSafe',supplier:'Metro Pet Goods',cost:330,price:550,stock:0,reorder:4,expiry:'',batch:'',location:'C4'},
  {id:6,name:'Full Grooming',sku:'SVC-GROOM',barcode:'',category:'Services',brand:'Pet Express',supplier:'',cost:0,price:650,stock:999,reorder:0,expiry:'',batch:'',location:''},
  {id:7,name:'Bath & Dry',sku:'SVC-BATH',barcode:'',category:'Services',brand:'Pet Express',supplier:'',cost:0,price:380,stock:999,reorder:0,expiry:'',batch:'',location:''}
 ],
 bookings:[
  {id:101,date:TODAY,time:'09:00',customerId:1,petId:1,service:'Grooming',staff:'Carlo Mendoza',duration:60,price:650,notes:'Hypoallergenic shampoo',status:'CONFIRMED'},
  {id:102,date:TODAY,time:'11:00',customerId:2,petId:2,service:'Pet spa',staff:'Carlo Mendoza',duration:75,price:850,notes:'Low-noise dryer',status:'CHECKED IN'},
  {id:103,date:TODAY,time:'14:00',customerId:3,petId:3,service:'Bath',staff:'Carlo Mendoza',duration:45,price:380,notes:'Deshedding shampoo',status:'READY FOR PICKUP'}
 ],
 sales:[{id:1,date:TODAY,total:1240,payment:'GCash',customerId:1,items:[{name:'Premium Dog Food 2kg',qty:1,price:780},{name:'Bath & Dry',qty:1,price:380}]},{id:2,date:TODAY,total:780,payment:'Cash',customerId:3,items:[{name:'Premium Dog Food 2kg',qty:1,price:780}]}],
 notifications:[{id:1,text:'Milo booking confirmed for today at 9:00 AM.',read:false},{id:2,text:'Pet Shampoo 500ml is low in stock.',read:false},{id:3,text:'Bruno is ready for pickup.',read:false}]
};
let db=JSON.parse(localStorage.getItem('petExpressOS-v1')||'null')||structuredClone(seed);
let cart=[];
const save=()=>{localStorage.setItem('petExpressOS-v1',JSON.stringify(db));renderAll()};
const money=n=>'₱'+Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
const customer=id=>db.customers.find(x=>x.id==id);
const pet=id=>db.pets.find(x=>x.id==id);
const notify=text=>{db.notifications.unshift({id:Date.now(),text,read:false});localStorage.setItem('petExpressOS-v1',JSON.stringify(db));renderNotifications();};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)}
function fallbackLogo(){const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='480' height='280' viewBox='0 0 480 280'><rect width='480' height='280' fill='#ffc514'/><text x='240' y='105' text-anchor='middle' font-family='Arial Rounded MT Bold,Arial' font-size='82' font-weight='900' fill='#ff2440'>Pet</text><text x='240' y='185' text-anchor='middle' font-family='Arial Rounded MT Bold,Arial' font-size='72' font-weight='900' fill='#1266c3'>Express</text><text x='240' y='225' text-anchor='middle' font-family='Arial' font-size='24' font-weight='700' fill='#1266c3'>The Dog &amp; Cat Shop</text></svg>`;$('#petExpressLogo').src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
const navItems=[['dashboard','🏠','Dashboard'],['bookings','📅','Bookings'],['pos','🛒','POS'],['customers','👤','Customers'],['pets','🐾','Pets'],['inventory','📦','Inventory'],['staff','👥','Staff'],['rewards','⭐','Rewards'],['reports','📊','Reports'],['checkin','✅','Check-In'],['hub','📱','Customer Hub'],['notifications','🔔','Notifications'],['settings','⚙️','Settings']];
function buildNav(){const side=$('#sidebar'),mobile=$('#mobileNav');side.innerHTML=navItems.map(([id,ic,t])=>`<button class='side-button' data-nav='${id}'>${ic}<span>${t}</span></button>`).join('');mobile.innerHTML=navItems.slice(0,5).map(([id,ic,t])=>`<button data-nav='${id}'>${ic}<br>${t}</button>`).join('')}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function badge(s){let c=['COMPLETED','READY FOR PICKUP','IN STOCK'].includes(s)?'green':['REQUESTED','CONFIRMED','LOW STOCK'].includes(s)?'orange':['OUT OF STOCK','CANCELLED','NO SHOW'].includes(s)?'red':'blue';return `<span class='badge ${c}'>${s}</span>`}
function inventoryStatus(p){if(p.category==='Services')return 'IN STOCK';if(p.stock<=0)return 'OUT OF STOCK';if(p.stock<=p.reorder)return 'LOW STOCK';if(p.expiry){const d=(new Date(p.expiry)-new Date())/86400000;if(d>=0&&d<=60)return 'EXPIRING SOON'}return 'IN STOCK'}
function renderDashboard(){const todayB=db.bookings.filter(b=>b.date===TODAY),todayS=db.sales.filter(s=>s.date===TODAY),rev=todayS.reduce((a,s)=>a+s.total,0),stats=[['Today’s bookings',todayB.length,'Appointments on schedule'],['Today’s sales',todayS.length,'Completed transactions'],['Customers served',todayS.length,'POS customers today'],['Pets currently booked',todayB.filter(b=>!['COMPLETED','CANCELLED','NO SHOW'].includes(b.status)).length,'Active appointments'],['Low-stock items',db.products.filter(p=>inventoryStatus(p)!=='IN STOCK'&&p.category!=='Services').length,'Needs inventory attention'],['Pending payments',1,'Demo pending payment'],['Staff on duty',db.staff.filter(s=>s.on).length,'Currently available'],['Revenue today',money(rev),'From completed sales']];$('#dashboardStats').innerHTML=stats.map(s=>`<div class='stat'><div class='label'>${s[0]}</div><div class='value'>${s[1]}</div><div class='sub'>${s[2]}</div></div>`).join('');$('#todayText').textContent=new Date().toLocaleDateString('en-PH',{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('#todaySchedule').innerHTML=todayB.length?todayB.sort((a,b)=>a.time.localeCompare(b.time)).map(b=>`<div class='schedule-row'><div class='time-box'>${b.time}</div><div><strong>${pet(b.petId)?.name||'Pet'} · ${b.service}</strong><div class='muted'>${customer(b.customerId)?.name||''} · ${b.staff}</div></div>${badge(b.status)}</div>`).join(''):`<div class='empty'>No bookings today.</div>`;const alerts=db.products.filter(p=>p.category!=='Services'&&inventoryStatus(p)!=='IN STOCK');$('#attentionList').innerHTML=alerts.length?alerts.map(p=>`<div class='schedule-row'><div class='avatar'>📦</div><div><strong>${p.name}</strong><div class='muted'>Stock ${p.stock} · Reorder ${p.reorder}</div></div>${badge(inventoryStatus(p))}</div>`).join(''):`<div class='empty'>No urgent alerts.</div>`}
function renderBookings(){const q=($('#bookingSearch').value||'').toLowerCase(),st=$('#bookingStatus').value,dt=$('#bookingDate').value;const rows=db.bookings.filter(b=>{const c=customer(b.customerId),p=pet(b.petId);return(!q||[c?.name,p?.name,b.service,b.staff].join(' ').toLowerCase().includes(q))&&(!st||b.status===st)&&(!dt||b.date===dt)}).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#bookingsTable').innerHTML=`<div class='table-wrap'><table class='data-table'><thead><tr><th>Date / Time</th><th>Customer</th><th>Pet</th><th>Service</th><th>Staff</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(b=>`<tr><td>${b.date}<div class='muted'>${b.time} · ${b.duration} min</div></td><td>${customer(b.customerId)?.name||''}</td><td><strong>${pet(b.petId)?.name||''}</strong></td><td>${b.service}<div class='muted'>${money(b.price)}</div></td><td>${b.staff}</td><td>${badge(b.status)}</td><td><button class='btn small' onclick='advanceBooking(${b.id})'>Next</button> <button class='btn small ghost' onclick='deleteBooking(${b.id})'>Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function renderProducts(){const q=($('#productSearch').value||'').toLowerCase(),cat=$('#productCategory').value;const items=db.products.filter(p=>(!cat||p.category===cat)&&(!q||[p.name,p.sku,p.barcode].join(' ').toLowerCase().includes(q)));$('#productGrid').innerHTML=items.map(p=>`<button class='product' onclick='addCart(${p.id})' ${p.stock===0&&p.category!=='Services'?'disabled':''}><div><span class='badge'>${p.category}</span><div class='product-name'>${p.name}</div><div class='muted'>${p.sku}${p.category!=='Services'?' · Stock '+p.stock:''}</div></div><div class='price'>${money(p.price)}</div></button>`).join('')}
function addCart(id){const p=db.products.find(x=>x.id===id),existing=cart.find(x=>x.id===id);if(!p)return;if(p.category!=='Services'&&p.stock<=0)return toast('Out of stock');if(existing)existing.qty++;else cart.push({id:p.id,name:p.name,price:p.price,qty:1,category:p.category});renderCart()}
function renderCart(){const d=Number($('#discount').value||0),subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0),total=subtotal*(1-Math.min(100,d)/100);$('#cartLines').innerHTML=cart.length?cart.map((i,k)=>`<div class='cart-line'><div><strong>${i.name}</strong><div class='muted'>${money(i.price)}</div></div><div class='qty-controls'><button class='icon-button' onclick='cartQty(${k},-1)'>−</button><b>${i.qty}</b><button class='icon-button' onclick='cartQty(${k},1)'>+</button></div><button class='icon-button' onclick='cartRemove(${k})'>✕</button></div>`).join(''):`<div class='empty'>Cart is empty.</div>`;$('#cartTotal').textContent=money(total)}
function cartQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);renderCart()} function cartRemove(i){cart.splice(i,1);renderCart()}
function checkout(){if(!cart.length)return toast('Add an item first.');const disc=Number($('#discount').value||0),total=cart.reduce((a,i)=>a+i.price*i.qty,0)*(1-Math.min(100,disc)/100),customerId=Number($('#posCustomer').value||0)||null;for(const line of cart){const p=db.products.find(x=>x.id===line.id);if(p&&p.category!=='Services')p.stock=Math.max(0,p.stock-line.qty)}db.sales.push({id:Date.now(),date:TODAY,total,payment:$('#paymentMethod').value,customerId,items:structuredClone(cart)});if(customerId){const c=customer(customerId);c.spend=(c.spend||0)+total;c.visits=(c.visits||0)+1;c.points=(c.points||0)+Math.floor(total/100)}notify(`New ${$('#paymentMethod').value} sale completed: ${money(total)}.`);cart=[];save();renderCart();toast('Sale completed · '+money(total))}
function renderCustomers(){const q=($('#customerSearch').value||'').toLowerCase();const rows=db.customers.filter(c=>!q||[c.name,c.mobile,c.email].join(' ').toLowerCase().includes(q));$('#customersTable').innerHTML=`<div class='table-wrap'><table class='data-table'><thead><tr><th>Customer</th><th>Mobile</th><th>Pets</th><th>Visits</th><th>Total Spending</th><th>Rewards</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${c.name}</strong><div class='muted'>${c.email||''}</div></td><td>${c.mobile||''}</td><td>${db.pets.filter(p=>p.ownerId===c.id).map(p=>p.name).join(', ')||'—'}</td><td>${c.visits||0}</td><td>${money(c.spend||0)}</td><td>${c.points||0} pts</td><td><button class='btn small ghost' onclick='deleteCustomer(${c.id})'>Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function renderPets(){const q=($('#petSearch').value||'').toLowerCase(),type=$('#petType').value;const arr=db.pets.filter(p=>(!type||p.type===type)&&(!q||[p.name,p.breed,customer(p.ownerId)?.name].join(' ').toLowerCase().includes(q)));$('#petList').innerHTML=arr.length?arr.map(p=>`<div class='list-card'><div class='avatar'>${p.type==='Cat'?'🐱':'🐶'}</div><div><strong>${p.name}</strong><div class='muted'>${p.breed} · ${p.sex} · ${customer(p.ownerId)?.name||'No owner'}</div><div class='muted'>${p.weight||'No weight'} · Preferred groomer: ${p.preferred||'Any'}</div>${p.allergies&&p.allergies!=='None known'?`<div class='warning'>⚠ Allergy: ${p.allergies} · ${p.emergency||p.grooming||''}</div>`:''}</div><div class='actions-inline'>${badge(p.vaccination||'No vaccine data')}</div></div>`).join(''):`<div class='empty'>No pets found.</div>`}
function renderInventory(){const q=($('#inventorySearch').value||'').toLowerCase(),st=$('#inventoryStatus').value;const arr=db.products.filter(p=>p.category!=='Services'&&(!q||[p.name,p.sku,p.brand].join(' ').toLowerCase().includes(q))&&(!st||inventoryStatus(p)===st));$('#inventoryTable').innerHTML=`<div class='table-wrap'><table class='data-table'><thead><tr><th>Product</th><th>SKU</th><th>Brand</th><th>Stock</th><th>Reorder</th><th>Cost / Price</th><th>Expiry</th><th>Status</th><th></th></tr></thead><tbody>${arr.map(p=>`<tr><td><strong>${p.name}</strong><div class='muted'>${p.category}</div></td><td>${p.sku}</td><td>${p.brand||'—'}</td><td>${p.stock}</td><td>${p.reorder}</td><td>${money(p.cost)} / ${money(p.price)}</td><td>${p.expiry||'—'}</td><td>${badge(inventoryStatus(p))}</td><td><button class='btn small ghost' onclick='stockIn(${p.id})'>Stock In</button></td></tr>`).join('')}</tbody></table></div>`}
function renderStaff(){const list=$('#staffList');list.innerHTML=db.staff.map(s=>`<div class='schedule-row'><div class='avatar'>👤</div><div><strong>${s.name}</strong><div class='muted'>${s.role}</div></div>${badge(s.on?'ON DUTY':'OFF DUTY')}</div>`).join('');$('#groomerQueue').innerHTML=db.bookings.filter(b=>!['COMPLETED','CANCELLED','NO SHOW'].includes(b.status)).map(b=>`<div class='schedule-row'><div class='time-box'>${b.time}</div><div><strong>${pet(b.petId)?.name} · ${b.service}</strong><div class='muted'>${b.staff} · ${b.status}</div></div><button class='btn small' onclick='advanceBooking(${b.id})'>Update</button></div>`).join('')}
function renderRewards(){const sel=$('#rewardCustomer');if(!sel.options.length||sel.options.length!==db.customers.length)sel.innerHTML=db.customers.map(c=>`<option value='${c.id}'>${c.name}</option>`).join('');const c=customer(Number(sel.value||db.customers[0]?.id));$('#rewardDetails').innerHTML=c?`<div class='stat'><div class='label'>Points Balance</div><div class='value'>${c.points||0}</div><div class='sub'>${c.name}</div></div><div class='reward-card'><span>🎂</span><div><strong>Birthday Reward</strong><p>Demo reward status: available</p></div></div>`:''}
function renderReports(){const salesTotal=db.sales.reduce((a,s)=>a+s.total,0),today=db.sales.filter(s=>s.date===TODAY).reduce((a,s)=>a+s.total,0),profit=db.sales.reduce((a,s)=>a+s.total*.34,0);$('#reportStats').innerHTML=[['Daily Sales',money(today)],['All Demo Sales',money(salesTotal)],['Repeat Customers','68%'],['Profit Estimate',money(profit)]].map(x=>`<div class='stat'><div class='label'>${x[0]}</div><div class='value'>${x[1]}</div></div>`).join('');const cats={};for(const s of db.sales)for(const i of s.items||[])cats[i.category||'Retail']=(cats[i.category||'Retail']||0)+i.price*i.qty;const max=Math.max(1,...Object.values(cats));$('#salesBars').innerHTML=Object.entries(cats).map(([k,v])=>`<div class='bar-row'><b>${k}</b><div class='bar-track'><div class='bar-fill' style='width:${v/max*100}%'></div></div><span>${money(v)}</span></div>`).join('')||`<div class='empty'>No sales yet.</div>`;const svc={};db.bookings.forEach(b=>svc[b.service]=(svc[b.service]||0)+1);const sm=Math.max(1,...Object.values(svc));$('#serviceBars').innerHTML=Object.entries(svc).map(([k,v])=>`<div class='bar-row'><b>${k}</b><div class='bar-track'><div class='bar-fill' style='width:${v/sm*100}%'></div></div><span>${v}</span></div>`).join('')}
function renderCheckin(){const q=($('#checkinSearch').value||'').toLowerCase();const arr=db.bookings.filter(b=>b.date===TODAY&&!['COMPLETED','CANCELLED','NO SHOW'].includes(b.status)).filter(b=>!q||[customer(b.customerId)?.name,customer(b.customerId)?.mobile,pet(b.petId)?.name].join(' ').toLowerCase().includes(q));$('#checkinList').innerHTML=arr.map(b=>`<div class='list-card'><div class='avatar'>${pet(b.petId)?.type==='Cat'?'🐱':'🐶'}</div><div><strong>${pet(b.petId)?.name} · ${customer(b.customerId)?.name}</strong><div class='muted'>${b.time} · ${b.service} · ${b.status}</div></div><button class='btn ${b.status==='CHECKED IN'?'ghost':''}' onclick='checkIn(${b.id})'>${b.status==='CHECKED IN'?'CHECKED IN':'CHECK IN'}</button></div>`).join('')||`<div class='empty'>No matching active booking.</div>`}
function renderHub(){const upcoming=db.bookings.filter(b=>!['COMPLETED','CANCELLED','NO SHOW'].includes(b.status)).slice(0,4);$('#hubBookings').innerHTML=upcoming.map(b=>`<div class='schedule-row'><div class='time-box'>${b.time}</div><div><strong>${pet(b.petId)?.name}</strong><div class='muted'>${b.date} · ${b.service}</div></div>${badge(b.status)}</div>`).join('')||`<div class='empty'>No upcoming appointments.</div>`;$('#hubRewards').innerHTML=db.customers.slice(0,3).map(c=>`<div class='schedule-row'><div class='avatar'>⭐</div><div><strong>${c.name}</strong><div class='muted'>${c.points||0} points</div></div></div>`).join('')}
function renderNotifications(){const unread=db.notifications.filter(n=>!n.read).length;$('#notificationCount').textContent=unread;$('#notificationList').innerHTML=db.notifications.length?db.notifications.map(n=>`<div class='schedule-row'><div class='avatar'>🔔</div><div><strong>${n.text}</strong><div class='muted'>${n.read?'Read':'Unread'}</div></div>${n.read?'':badge('NEW')}</div>`).join(''):`<div class='empty'>No notifications.</div>`}
function populateSelects(){const cats=[...new Set(db.products.map(p=>p.category))];$('#productCategory').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('#bookingStatus').innerHTML='<option value="">All statuses</option>'+STATUS.map(s=>`<option>${s}</option>`).join('');$('#posCustomer').innerHTML='<option value="">Walk-in customer</option>'+db.customers.map(c=>`<option value='${c.id}'>${c.name}</option>`).join('')}
function openModal(title,html,onSubmit){$('#modalTitle').textContent=title;const form=$('#modalForm');form.innerHTML=html+`<div class='actions span-2' style='justify-content:flex-end;margin-top:8px'><button type='button' class='btn ghost' onclick='closeModal()'>Cancel</button><button class='btn' type='submit'>Save</button></div>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');form.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(form))}}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function modalBooking(){openModal('New Booking',`<div class='form-grid'><label class='field'><span>Customer</span><select name='customer' class='control' required>${db.customers.map(c=>`<option value='${c.id}'>${c.name}</option>`).join('')}</select></label><label class='field'><span>Pet</span><select name='pet' class='control' required>${db.pets.map(p=>`<option value='${p.id}'>${p.name}</option>`).join('')}</select></label><label class='field'><span>Service</span><select name='service' class='control'>${['Grooming','Bath','Nail trimming','Ear cleaning','Pet spa','Vet appointment','Boarding','Daycare','Other'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class='field'><span>Date</span><input name='date' class='control' type='date' value='${TODAY}' required></label><label class='field'><span>Time</span><input name='time' class='control' type='time' value='10:00' required></label><label class='field'><span>Assigned staff</span><select name='staff' class='control'>${db.staff.filter(s=>['GROOMER','PET CARE STAFF','MANAGER'].includes(s.role)).map(s=>`<option>${s.name}</option>`).join('')}</select></label><label class='field'><span>Duration (minutes)</span><input name='duration' class='control' type='number' value='60'></label><label class='field'><span>Price</span><input name='price' class='control' type='number' value='650'></label><label class='field span-2'><span>Notes</span><textarea name='notes' class='control'></textarea></label></div>`,fd=>{const date=fd.get('date'),time=fd.get('time'),staff=fd.get('staff');if(db.bookings.some(b=>b.date===date&&b.time===time&&b.staff===staff&&!['CANCELLED','NO SHOW','COMPLETED'].includes(b.status)))return toast('Double-booking blocked for that staff/time.');db.bookings.push({id:Date.now(),date,time,customerId:Number(fd.get('customer')),petId:Number(fd.get('pet')),service:fd.get('service'),staff,duration:Number(fd.get('duration')),price:Number(fd.get('price')),notes:fd.get('notes'),status:'REQUESTED'});notify(`New booking requested for ${pet(Number(fd.get('pet')))?.name}.`);save();closeModal();go('bookings');toast('Booking created')})}
function modalCustomer(){openModal('Add Customer',`<div class='form-grid'><label class='field'><span>Full Name</span><input name='name' class='control' required></label><label class='field'><span>Mobile</span><input name='mobile' class='control'></label><label class='field'><span>Email</span><input name='email' class='control' type='email'></label><label class='field'><span>Address</span><input name='address' class='control'></label><label class='field span-2'><span>Notes</span><textarea name='notes' class='control'></textarea></label></div>`,fd=>{db.customers.push({id:Date.now(),name:fd.get('name'),mobile:fd.get('mobile'),email:fd.get('email'),address:fd.get('address'),notes:fd.get('notes'),visits:0,spend:0,points:0});save();closeModal();go('customers');toast('Customer added')})}
function modalPet(){openModal('Add Pet',`<div class='form-grid'><label class='field'><span>Pet Name</span><input name='name' class='control' required></label><label class='field'><span>Dog / Cat</span><select name='type' class='control'><option>Dog</option><option>Cat</option></select></label><label class='field'><span>Breed</span><input name='breed' class='control'></label><label class='field'><span>Sex</span><select name='sex' class='control'><option>Male</option><option>Female</option></select></label><label class='field'><span>Owner</span><select name='owner' class='control'>${db.customers.map(c=>`<option value='${c.id}'>${c.name}</option>`).join('')}</select></label><label class='field'><span>Weight</span><input name='weight' class='control'></label><label class='field'><span>Allergies</span><input name='allergies' class='control' placeholder='None known'></label><label class='field'><span>Temperament</span><input name='temperament' class='control'></label><label class='field span-2'><span>Emergency / Grooming Notes</span><textarea name='notes' class='control'></textarea></label></div>`,fd=>{db.pets.push({id:Date.now(),name:fd.get('name'),type:fd.get('type'),breed:fd.get('breed'),sex:fd.get('sex'),ownerId:Number(fd.get('owner')),weight:fd.get('weight'),allergies:fd.get('allergies')||'None known',temperament:fd.get('temperament'),grooming:fd.get('notes'),emergency:fd.get('notes'),vaccination:'Not entered',preferred:'Any'});save();closeModal();go('pets');toast('Pet profile added')})}
function modalInventory(){openModal('Add Inventory Product',`<div class='form-grid'><label class='field'><span>Product Name</span><input name='name' class='control' required></label><label class='field'><span>SKU</span><input name='sku' class='control' required></label><label class='field'><span>Category</span><input name='category' class='control' value='Pet Food'></label><label class='field'><span>Brand</span><input name='brand' class='control'></label><label class='field'><span>Cost</span><input name='cost' class='control' type='number'></label><label class='field'><span>Selling Price</span><input name='price' class='control' type='number'></label><label class='field'><span>Current Stock</span><input name='stock' class='control' type='number' value='0'></label><label class='field'><span>Reorder Level</span><input name='reorder' class='control' type='number' value='5'></label></div>`,fd=>{db.products.push({id:Date.now(),name:fd.get('name'),sku:fd.get('sku'),barcode:'',category:fd.get('category'),brand:fd.get('brand'),supplier:'',cost:Number(fd.get('cost')),price:Number(fd.get('price')),stock:Number(fd.get('stock')),reorder:Number(fd.get('reorder')),expiry:'',batch:'',location:''});save();closeModal();go('inventory');toast('Product added')})}
function modalStaff(){openModal('Add Staff',`<div class='form-grid'><label class='field'><span>Name</span><input name='name' class='control' required></label><label class='field'><span>Role</span><select name='role' class='control'>${['OWNER / ADMIN','MANAGER','CASHIER','GROOMER','PET CARE STAFF','INVENTORY STAFF'].map(x=>`<option>${x}</option>`).join('')}</select></label></div>`,fd=>{db.staff.push({id:Date.now(),name:fd.get('name'),role:fd.get('role'),on:true});save();closeModal();go('staff');toast('Staff member added')})}
window.advanceBooking=id=>{const b=db.bookings.find(x=>x.id===id),flow=['REQUESTED','CONFIRMED','CHECKED IN','IN SERVICE','READY FOR PICKUP','COMPLETED'];if(!b)return;const i=flow.indexOf(b.status);b.status=flow[Math.min(flow.length-1,Math.max(0,i+1))];notify(`${pet(b.petId)?.name}: ${b.status}.`);save();toast('Booking updated')};
window.deleteBooking=id=>{if(confirm('Delete this booking?')){db.bookings=db.bookings.filter(x=>x.id!==id);save()}};
window.deleteCustomer=id=>{if(confirm('Delete this customer record?')){db.customers=db.customers.filter(x=>x.id!==id);save()}};
window.stockIn=id=>{const q=Number(prompt('Quantity to add:','10'));if(q>0){const p=db.products.find(x=>x.id===id);p.stock+=q;save();toast('Stock updated')}};
window.checkIn=id=>{const b=db.bookings.find(x=>x.id===id);if(!b)return;b.status='CHECKED IN';b.arrival=new Date().toLocaleTimeString();notify(`${pet(b.petId)?.name} checked in at ${b.arrival}.`);save();toast('Pet checked in')};
window.addCart=addCart;window.cartQty=cartQty;window.cartRemove=cartRemove;window.closeModal=closeModal;
function exportJSON(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='pet-express-os-backup.json';a.click();URL.revokeObjectURL(a.href)}
function exportCSV(){const lines=['Date,Total,Payment,Customer',...db.sales.map(s=>[s.date,s.total,s.payment,customer(s.customerId)?.name||'Walk-in'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='pet-express-sales.csv';a.click();URL.revokeObjectURL(a.href)}
function renderAll(){populateSelects();renderDashboard();renderBookings();renderProducts();renderCart();renderCustomers();renderPets();renderInventory();renderStaff();renderRewards();renderReports();renderCheckin();renderHub();renderNotifications()}
function wire(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)go(nav.dataset.nav);const act=e.target.closest('[data-action]')?.dataset.action;if(act==='new-booking')modalBooking();if(act==='new-customer')modalCustomer();if(act==='new-pet')modalPet();if(act==='new-inventory')modalInventory();if(act==='new-staff')modalStaff()});['bookingSearch','bookingStatus','bookingDate'].forEach(id=>$('#'+id).addEventListener('input',renderBookings));$('#clearBookingFilters').onclick=()=>{$('#bookingSearch').value='';$('#bookingStatus').value='';$('#bookingDate').value='';renderBookings()};['productSearch','productCategory'].forEach(id=>$('#'+id).addEventListener('input',renderProducts));$('#discount').addEventListener('input',renderCart);$('#checkoutButton').onclick=checkout;$('#transactionHistoryButton').onclick=()=>toast(`${db.sales.length} demo transaction(s) recorded`);$('#customerSearch').addEventListener('input',renderCustomers);['petSearch','petType'].forEach(id=>$('#'+id).addEventListener('input',renderPets));['inventorySearch','inventoryStatus'].forEach(id=>$('#'+id).addEventListener('input',renderInventory));$('#rewardCustomer').addEventListener('change',renderRewards);$('#checkinSearch').addEventListener('input',renderCheckin);$('#notificationButton').onclick=()=>go('notifications');$('#markReadButton').onclick=()=>{db.notifications.forEach(n=>n.read=true);save();toast('Notifications marked read')};$('#printReportButton').onclick=()=>window.print();$('#downloadCsvButton').onclick=exportCSV;$('#exportJsonButton').onclick=exportJSON;$('#importJsonInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();toast('Backup imported')}catch{toast('Invalid JSON file')}};r.readAsText(f)};$('#resetButton').onclick=()=>{if(confirm('Reset all demo data on this device?')){db=structuredClone(seed);localStorage.removeItem('petExpressOS-v1');save();go('dashboard');toast('Demo data reset')}};$('#closeModalButton').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()})}
buildNav();fallbackLogo();wire();renderAll();go('dashboard');