(()=>{
const DKEY='petExpressDemoUpgrade-v1', SKEY='petExpressDemoSession-v1';
const roles={
 'OWNER / ADMIN':{icon:'👑',desc:'Full access to every module',allow:'*'},
 'MANAGER':{icon:'📊',desc:'Operations, staff, reports, approvals',allow:['dashboard','bookings','customers','pets','inventory','staff','rewards','reports','checkin','notifications','settings','calendar','boarding','suppliers','approvals','audit']},
 'RECEPTION':{icon:'🛎️',desc:'Bookings, customers, pets, check-in & pickup',allow:['dashboard','bookings','customers','pets','checkin','hub','notifications','calendar','boarding']},
 'CASHIER':{icon:'🧾',desc:'POS, receipts, payments & rewards',allow:['dashboard','pos','customers','rewards','notifications']},
 'GROOMER':{icon:'✂️',desc:'Assigned pets, care notes & service status',allow:['dashboard','bookings','pets','staff','notifications','calendar']},
 'PET CARE STAFF':{icon:'🐾',desc:'Boarding, daycare, feeding & medication logs',allow:['dashboard','pets','notifications','boarding']},
 'INVENTORY STAFF':{icon:'📦',desc:'Inventory, suppliers, receiving & adjustments',allow:['dashboard','inventory','notifications','suppliers','audit']}
};
const defaults={
 suppliers:[{id:1,name:'Paws Supply Co.',contact:'Mia Navarro',mobile:'0917 555 1212',terms:'30 days',status:'ACTIVE'},{id:2,name:'Happy Tails Trading',contact:'Luis Ramos',mobile:'0918 555 3322',terms:'COD',status:'ACTIVE'}],
 purchaseOrders:[{id:'PO-24019',supplier:'Paws Supply Co.',total:12400,status:'SENT',eta:'2026-09-14'},{id:'PO-24018',supplier:'Happy Tails Trading',total:7850,status:'PARTIALLY RECEIVED',eta:'2026-09-12'}],
 boarding:[{id:1,pet:'Milo',owner:'Maria Santos',area:'Daycare D-02',until:'5:30 PM',feed:'12:00 PM',med:'None',status:'PLAYTIME'},{id:2,pet:'Luna',owner:'James Cruz',area:'Boarding B-04',until:'Tomorrow 10:00 AM',feed:'6:00 PM',med:'8:00 PM',status:'REST'}],
 approvals:[{id:1,type:'Inventory adjustment',requester:'Rica Flores',detail:'Pet Shampoo 500ml: -2 damaged',status:'PENDING'},{id:2,type:'Discount request',requester:'Bea Lim',detail:'15% grooming promo override',status:'PENDING'}],
 audit:[{id:Date.now()-500000,user:'Anna Dela Cruz',role:'MANAGER',action:'Viewed manager report',record:'REPORTS',time:new Date(Date.now()-500000).toISOString()},{id:Date.now()-350000,user:'Carlo Mendoza',role:'GROOMER',action:'Marked Luna checked in',record:'BOOKING #102',time:new Date(Date.now()-350000).toISOString()}],
 careLogs:[{id:1,pet:'Milo',type:'Fed',time:'12:02 PM',staff:'Noel Garcia'},{id:2,pet:'Luna',type:'Rest',time:'11:35 AM',staff:'Noel Garcia'}]
};
let ext=JSON.parse(localStorage.getItem(DKEY)||'null')||structuredClone(defaults);
const persist=()=>{localStorage.setItem(DKEY,JSON.stringify(ext));try{bc?.postMessage('sync')}catch{}};
const bc=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('pet-express-demo'):null;
function log(action,record='SYSTEM'){const s=getSession();ext.audit.unshift({id:Date.now(),user:s?.name||'Demo User',role:s?.role||'DEMO',action,record,time:new Date().toISOString()});ext.audit=ext.audit.slice(0,100);persist();}
function getSession(){try{return JSON.parse(sessionStorage.getItem(SKEY)||'null')}catch{return null}}
function setSession(s){sessionStorage.setItem(SKEY,JSON.stringify(s));applyRole();renderDemoPages();}
function logout(){log('Logged out');sessionStorage.removeItem(SKEY);location.reload()}
function ensureLogin(){if(getSession())return;const gate=document.createElement('div');gate.className='login-gate';gate.innerHTML=`<div class="login-card"><div class="login-brand"><img src="pet-express-logo.jpg" alt="Pet Express logo"><div><h2>Pet Express OS — Demo Login</h2><p>Choose a staff role to enter the client presentation.</p></div></div><div class="role-grid">${Object.entries(roles).map(([r,v])=>`<button class="role-card" data-role="${r}"><div class="role-icon">${v.icon}</div><b>${r}</b><span>${v.desc}</span></button>`).join('')}</div><div class="login-note"><b>DEMO MODE:</b> one-tap role access, simulated permissions, local demo persistence and browser-tab synchronization. No production credentials are used.</div></div>`;document.body.appendChild(gate);gate.addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(!b)return;const role=b.dataset.role;const names={'OWNER / ADMIN':'Alex Rivera','MANAGER':'Anna Dela Cruz','RECEPTION':'Sofia Reyes','CASHIER':'Bea Lim','GROOMER':'Carlo Mendoza','PET CARE STAFF':'Noel Garcia','INVENTORY STAFF':'Rica Flores'};sessionStorage.setItem(SKEY,JSON.stringify({role,name:names[role],loginAt:Date.now()}));ext.audit.unshift({id:Date.now(),user:names[role],role,action:'Logged in to demo',record:'SESSION',time:new Date().toISOString()});persist();gate.remove();decorateTop();installDemoNav();applyRole();renderDemoPages();});}
function decorateTop(){const top=document.querySelector('.top-actions');if(!top||document.getElementById('demoUser'))return;const s=getSession();const search=document.createElement('div');search.className='global-search-wrap';search.innerHTML=`<input id="globalDemoSearch" placeholder="Search customer, pet, booking, SKU…"><div id="globalDemoResults" class="global-results"></div>`;top.prepend(search);const badge=document.createElement('span');badge.className='demo-badge';badge.innerHTML='<span class="sync-dot"></span> Cloud Sync · DEMO';top.appendChild(badge);const user=document.createElement('div');user.id='demoUser';user.className='demo-user';user.innerHTML=`<div><strong>${s?.name||'Demo User'}</strong><small>${s?.role||'DEMO'}</small></div><button id="demoLogout">Logout</button>`;top.appendChild(user);document.getElementById('demoLogout').onclick=logout;const input=document.getElementById('globalDemoSearch'),results=document.getElementById('globalDemoResults');input.addEventListener('input',()=>renderGlobalSearch(input.value,results));document.addEventListener('click',e=>{if(!search.contains(e.target))results.classList.remove('show')});}
function renderGlobalSearch(q,out){q=q.trim().toLowerCase();if(!q){out.classList.remove('show');return}let rows=[];try{rows.push(...db.customers.filter(x=>[x.name,x.mobile,x.email].join(' ').toLowerCase().includes(q)).map(x=>({t:x.name,s:`Customer · ${x.mobile}`,nav:'customers'})));rows.push(...db.pets.filter(x=>[x.name,x.breed].join(' ').toLowerCase().includes(q)).map(x=>({t:x.name,s:`Pet · ${x.breed}`,nav:'pets'})));rows.push(...db.bookings.filter(x=>String(x.id).includes(q)||[x.service,x.staff].join(' ').toLowerCase().includes(q)).map(x=>({t:`Booking #${x.id}`,s:`${x.service} · ${x.date} ${x.time}`,nav:'bookings'})));rows.push(...db.products.filter(x=>[x.name,x.sku,x.barcode].join(' ').toLowerCase().includes(q)).map(x=>({t:x.name,s:`${x.sku} · Stock ${x.stock}`,nav:'inventory'})));}catch{}out.innerHTML=rows.slice(0,12).map(r=>`<button class="global-result" data-open="${r.nav}"><b>${r.t}</b><small>${r.s}</small></button>`).join('')||'<div class="global-result"><b>No matches</b><small>Try another search.</small></div>';out.classList.add('show');out.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(typeof go==='function')go(b.dataset.open);out.classList.remove('show')});}
const demoModules=[['calendar','🗓️','Calendar'],['boarding','🏨','Boarding'],['suppliers','🚚','Suppliers'],['approvals','✅','Approvals'],['audit','🛡️','Audit Log']];
function installDemoNav(){const side=document.getElementById('sidebar');if(!side||side.querySelector('[data-demo-nav]'))return;demoModules.forEach(([id,ic,label])=>{const b=document.createElement('button');b.className='side-button';b.dataset.demoNav=id;b.innerHTML=`${ic}<span>${label}</span>`;side.appendChild(b)});side.addEventListener('click',e=>{const b=e.target.closest('[data-demo-nav]');if(!b)return;openDemoPage(b.dataset.demoNav)});const main=document.querySelector('.main');demoModules.forEach(([id])=>{const sec=document.createElement('section');sec.id='demo-'+id;sec.className='page demo-page';main.insertBefore(sec,main.querySelector('footer'))});}
function allowed(id){const s=getSession(),cfg=roles[s?.role||'OWNER / ADMIN'];return cfg?.allow==='*'||cfg?.allow?.includes(id)}
function applyRole(){const s=getSession();if(!s)return;document.querySelectorAll('[data-nav]').forEach(b=>{const id=b.dataset.nav;b.classList.toggle('permission-locked',!allowed(id));b.title=!allowed(id)?`Locked for ${s.role}`:''});document.querySelectorAll('[data-demo-nav]').forEach(b=>{b.classList.toggle('permission-locked',!allowed(b.dataset.demoNav))});}
function openDemoPage(id){if(!allowed(id))return alert('This module is locked for the selected demo role.');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.demo-page').forEach(p=>p.classList.remove('active'));const sec=document.getElementById('demo-'+id);sec.classList.add('active');document.querySelectorAll('[data-nav],[data-demo-nav]').forEach(b=>b.classList.remove('active'));document.querySelector(`[data-demo-nav="${id}"]`)?.classList.add('active');renderDemoPages();window.scrollTo({top:0,behavior:'smooth'});}
function renderDemoPages(){renderCalendar();renderBoarding();renderSuppliers();renderApprovals();renderAudit()}
function renderCalendar(){const sec=document.getElementById('demo-calendar');if(!sec)return;let bookings=[];try{bookings=db.bookings||[]}catch{}const cols=['Carlo Mendoza','Sofia Reyes','Noel Garcia','Unassigned'];sec.innerHTML=`<div class="page-head"><div><h2>Appointment Calendar</h2><p>Demo day / week / month / staff scheduling with duration-aware appointments.</p></div><button class="btn" data-action="new-booking">+ New Booking</button></div><div class="card"><div class="calendar-tabs"><button class="active">DAY</button><button>WEEK</button><button>MONTH</button><button>STAFF SCHEDULE</button><span class="demo-pill">Drag & drop · DEMO</span><span class="demo-pill">Double-book protection · ON</span></div><div class="calendar-board">${cols.map(st=>`<div class="cal-col"><h4>${st}</h4>${bookings.filter(b=>(b.staff||'Unassigned')===st).map(b=>`<div class="cal-item"><strong>${b.time} · ${pet?.(b.petId)?.name||'Pet'}</strong><small>${b.service} · ${b.duration} min · ${b.status}</small></div>`).join('')||'<div class="cal-item"><small>Available schedule</small></div>'}</div>`).join('')}</div></div>`;}
function renderBoarding(){const sec=document.getElementById('demo-boarding');if(!sec)return;sec.innerHTML=`<div class="page-head"><div><h2>Boarding & Daycare</h2><p>Kennel assignment, feeding, medication and live care logs.</p></div><button class="btn" onclick="demoAddBoarding()">+ Check In Pet</button></div><div class="demo-grid">${ext.boarding.map(x=>`<div class="demo-card"><div class="demo-row"><div><strong>${x.pet}</strong><small>${x.owner}<br>${x.area} · Until ${x.until}</small></div><span class="demo-pill">${x.status}</span></div><p class="muted">Feeding: ${x.feed}<br>Medication: ${x.med}</p><div class="demo-actions"><button class="demo-btn yellow" onclick="demoCare('${x.pet}','Fed')">Fed</button><button class="demo-btn ghost" onclick="demoCare('${x.pet}','Walk completed')">Walk</button><button class="demo-btn ghost" onclick="demoCare('${x.pet}','Medication given')">Medication</button></div></div>`).join('')}</div><div class="card" style="margin-top:12px"><h3>Live Care Log</h3><div class="demo-list">${ext.careLogs.map(l=>`<div class="demo-row"><div><strong>${l.pet} · ${l.type}</strong><small>${l.time} · ${l.staff}</small></div></div>`).join('')}</div></div>`;}
function renderSuppliers(){const sec=document.getElementById('demo-suppliers');if(!sec)return;sec.innerHTML=`<div class="page-head"><div><h2>Suppliers & Purchasing</h2><p>Supplier records, purchase orders and receiving demo.</p></div><button class="btn" onclick="demoNewPO()">+ New Purchase Order</button></div><div class="split"><div class="card"><h3>Suppliers</h3><div class="demo-list">${ext.suppliers.map(s=>`<div class="demo-row"><div><strong>${s.name}</strong><small>${s.contact} · ${s.mobile}<br>Terms: ${s.terms}</small></div><span class="demo-pill">${s.status}</span></div>`).join('')}</div></div><div class="card"><h3>Purchase Orders</h3><div class="demo-list">${ext.purchaseOrders.map(p=>`<div class="demo-row"><div><strong>${p.id}</strong><small>${p.supplier}<br>ETA ${p.eta} · ₱${p.total.toLocaleString()}</small></div><div><span class="demo-pill">${p.status}</span><div class="demo-actions"><button class="demo-btn ghost" onclick="demoReceivePO('${p.id}')">Receive</button></div></div></div>`).join('')}</div></div></div>`;}
function renderApprovals(){const sec=document.getElementById('demo-approvals');if(!sec)return;sec.innerHTML=`<div class="page-head"><div><h2>Manager Approvals</h2><p>Refunds, discounts, price changes and stock adjustments.</p></div><span class="demo-pill">${ext.approvals.filter(a=>a.status==='PENDING').length} pending</span></div><div class="card"><div class="demo-list">${ext.approvals.map(a=>`<div class="demo-row"><div><strong>${a.type}</strong><small>${a.requester}<br>${a.detail}</small></div><div><span class="demo-pill">${a.status}</span>${a.status==='PENDING'?`<div class="demo-actions"><button class="demo-btn" onclick="demoApproval(${a.id},'APPROVED')">Approve</button><button class="demo-btn red" onclick="demoApproval(${a.id},'REJECTED')">Reject</button></div>`:''}</div></div>`).join('')}</div></div>`;}
function renderAudit(){const sec=document.getElementById('demo-audit');if(!sec)return;sec.innerHTML=`<div class="page-head"><div><h2>Audit Log</h2><p>Traceable activity history for the client presentation.</p></div><span class="demo-pill">DEMO AUDIT TRAIL</span></div><div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Record</th></tr></thead><tbody>${ext.audit.map(a=>`<tr><td>${new Date(a.time).toLocaleString('en-PH')}</td><td>${a.user}</td><td>${a.role}</td><td>${a.action}</td><td>${a.record}</td></tr>`).join('')}</tbody></table></div></div>`;}
window.demoCare=(petName,type)=>{const s=getSession();ext.careLogs.unshift({id:Date.now(),pet:petName,type,time:new Date().toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'}),staff:s?.name||'Demo Staff'});log(`${type} logged for ${petName}`,'CARE LOG');renderBoarding();};
window.demoAddBoarding=()=>{ext.boarding.unshift({id:Date.now(),pet:'New Demo Pet',owner:'Demo Customer',area:'Daycare D-03',until:'6:00 PM',feed:'3:00 PM',med:'None',status:'CHECKED IN'});log('Checked pet into daycare','BOARDING');renderBoarding();};
window.demoNewPO=()=>{const id='PO-'+String(Date.now()).slice(-5);ext.purchaseOrders.unshift({id,supplier:'Paws Supply Co.',total:5400,status:'DRAFT',eta:'2026-09-16'});log('Created purchase order',id);renderSuppliers();};
window.demoReceivePO=id=>{const p=ext.purchaseOrders.find(x=>x.id===id);if(p){p.status='RECEIVED';log('Received purchase order',id);renderSuppliers();}};
window.demoApproval=(id,status)=>{const a=ext.approvals.find(x=>x.id===id);if(a){a.status=status;log(`${status} ${a.type}`,'APPROVAL #'+id);renderApprovals();renderAudit();}};
function hookExistingActions(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav&&!allowed(nav.dataset.nav)){e.preventDefault();e.stopPropagation();alert('This module is locked for the selected demo role.');}},true);const oldSave=typeof save==='function'?save:null;if(oldSave){try{window.addEventListener('storage',e=>{if(e.key==='petExpressOS-v1'){try{db=JSON.parse(e.newValue);renderAll();toast('Demo sync received from another tab')}catch{}}});}catch{}}}
function boot(){ensureLogin();decorateTop();installDemoNav();applyRole();renderDemoPages();hookExistingActions();try{const logo=document.getElementById('petExpressLogo');if(logo&&!logo.getAttribute('src'))logo.src='pet-express-logo.jpg'}catch{}bc&&(bc.onmessage=()=>{ext=JSON.parse(localStorage.getItem(DKEY)||'null')||ext;renderDemoPages()});}
setTimeout(boot,80);
})();